"""menambahkan tampungHasil

Revision ID: 261fe98bca67
Revises: 69bcc6442495
Create Date: 2025-09-02 10:21:39.255486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261fe98bca67'
down_revision = '69bcc6442495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tampung_hasil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('kerjaAktual_turbin', sa.Float(), nullable=False),
    sa.Column('energiPanas_masuk', sa.Float(), nullable=False),
    sa.Column('efisiensi', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['data_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tampung_hasil')
    # ### end Alembic commands ###
