"""update level

Revision ID: 46cb8ed3b83d
Revises: ded95ac747c5
Create Date: 2025-09-01 10:28:58.976988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46cb8ed3b83d'
down_revision = 'ded95ac747c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_schema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.BigInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.drop_column('level')

    with op.batch_alter_table('data_schema', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
