"""menambahkan dan mengurangi data pada chemy

Revision ID: 69bcc6442495
Revises: 46cb8ed3b83d
Create Date: 2025-09-02 06:24:02.369317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69bcc6442495'
down_revision = '46cb8ed3b83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_schema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posisi', sa.String(length=50), nullable=False))
        batch_op.drop_column('jumlah_mol')
        batch_op.drop_column('volume')
        batch_op.drop_column('energi_dalam')
        batch_op.drop_column('entropi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_schema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entropi', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('energi_dalam', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('volume', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('jumlah_mol', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('posisi')

    # ### end Alembic commands ###
