"""add password upgrade

Revision ID: 7f453d93eb06
Revises: 5c480e9dd0c9
Create Date: 2025-08-26 23:39:31.936093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f453d93eb06'
down_revision = '5c480e9dd0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
