"""menambahkan data DataSchema

Revision ID: ded95ac747c5
Revises: 7f453d93eb06
Create Date: 2025-09-01 01:29:16.137276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded95ac747c5'
down_revision = '7f453d93eb06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_schema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suhu', sa.Float(), nullable=False),
    sa.Column('tekanan', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('entropi', sa.Float(), nullable=True),
    sa.Column('entalpi', sa.Float(), nullable=True),
    sa.Column('energi_dalam', sa.Float(), nullable=True),
    sa.Column('massa', sa.Float(), nullable=True),
    sa.Column('jumlah_mol', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['data_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_schema')
    # ### end Alembic commands ###
